name: "Build and push image AWS ECR"

on:
  push:
    paths:
      - "src/**"
      - "Dockerfile"
      - ".github/workflows/deploy.yml"

    branches: [master]

jobs:
  build:
    name: Build image
    runs-on: ubuntu-latest

    steps:
      - name: ✅Check out code
        uses: actions/checkout@v2

      - name: 🔧Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: ☁️Login AWS ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: 🛠️Build and Push image
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: nicolas/demo-app
          IMAGE_TAG: latest
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
